# Generated by Django 2.1.7 on 2021-08-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nm_projeto', models.CharField(max_length=255)),
                ('dt_inicio', models.DateTimeField(editable=False)),
                ('dt_fim', models.DateTimeField()),
            ],
            options={
                'db_table': 'projetos',
            },
        ),
    ]
