# Generated by Django 2.1.7 on 2021-08-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_auto_20210823_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='ind_finalizada',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
